apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::748527796092:user/edurekaUser
      username: edurekaUser
      groups:
        - system:masters
  mapRoles: |
    - rolearn: arn:aws:iam::748527796092:role/gitHubRole
      username: github-actions
      groups:
        - system:masters